# Generated by Django 3.0.4 on 2020-03-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Link',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('post_type', models.CharField(choices=[('SELF', 'Texto'), ('LINK', 'Link')], max_length=4, verbose_name='Tipo de Post')),
                ('creation_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de criação')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modificado')),
            ],
        ),
        migrations.CreateModel(
            name='PostKarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('downvotes', models.IntegerField(default=0, verbose_name='Downvotes')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='SelfPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=40000, verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Texto',
            },
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('creation_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de criação')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Subreddit',
                'verbose_name_plural': 'Subreddits',
            },
        ),
    ]
