# Generated by Django 3.0.4 on 2020-03-07 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0002_auto_20200307_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='thumbnail',
            field=models.ImageField(default='E:\\PycharmProjects\\BRedditmedia\\link_post.png', height_field='thumbnail_height', upload_to='thumbnail', width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='linkpost',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='linkpost',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='selfpost',
            name='thumbnail',
            field=models.ImageField(default='E:\\PycharmProjects\\BRedditmedia\\self_post.png', height_field='thumbnail_height', upload_to='thumbnail', width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='selfpost',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='selfpost',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
    ]
