# Generated by Django 3.0.4 on 2020-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0003_auto_20200307_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpost',
            name='thumbnail',
            field=models.ImageField(default='/static/img/link_default.png', height_field='thumbnail_height', upload_to='thumbnail', width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='selfpost',
            name='thumbnail',
            field=models.ImageField(default='/static/img/self_default.png', height_field='thumbnail_height', upload_to='thumbnail', width_field='thumbnail_width'),
        ),
    ]
