# Generated by Django 3.0.4 on 2020-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0004_auto_20200307_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpost',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='selfpost',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
