# Generated by Django 3.0.4 on 2020-03-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0009_auto_20200308_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='karma',
        ),
        migrations.DeleteModel(
            name='PostKarma',
        ),
    ]
