# Generated by Django 3.0.4 on 2020-03-08 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0010_auto_20200308_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=10000, verbose_name='Comentário')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subreddit.Post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userpostvote',
            options={'verbose_name': 'Voto do Post', 'verbose_name_plural': 'Votos do Post'},
        ),
        migrations.AlterField(
            model_name='userpostvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='UserCommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPVOTE', 'Upvoted'), ('DOWNVOTE', 'Downvoted'), ('UNVOTE', 'Unvoted')], max_length=10, verbose_name='Estado')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='subreddit.Comment', verbose_name='Comentário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Voto de Comentário',
                'verbose_name_plural': 'Votos de Comentário',
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
