# Generated by Django 3.0.4 on 2020-03-08 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0012_auto_20200308_1253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpostvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpostvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpostvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.DeleteModel(
            name='UserCommentVote',
        ),
        migrations.DeleteModel(
            name='UserPostVote',
        ),
    ]
