# Generated by Django 3.0.4 on 2020-03-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0013_auto_20200308_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Votos de Comentários', 'verbose_name_plural': 'Votos de Comentários'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Votos', 'verbose_name_plural': 'Votos de Usuário'},
        ),
    ]
